### ISSUE TITLE
Bad Image Requests

### ISSUE THREAD

**Issue by adrienp** [frimmy/api-test#2]
Sometimes the API returns movie results with `null` `poster_path`s. And when that happens you end up looking for the image at src: `http://d3gtl9l2a4fn1j.cloudfront.net/t/p/w342null`

It's happening here: https://github.com/frimmy/api-test/blob/master/app.js#L46

To reproduce, try searching `scary`

These cases should fail gracefully. Maybe try iterating through all results til you find one with a valid image url?

**Comment by frimmy** [comment]
nah that sounds dumb

**Comment by adrienp** [comment]
you're dumb
